Feature/create unknown device
diwise/iot-device-mgmt pull request #60
Opened 2024-01-15 11:53 UTC by ermhawi

2024-01-15 19:26 UTC, istyf requested changes
Se kommentarer

2024-01-15 19:26 UTC, istyf commented on pkg/client/client.go
> +
Du borde lägga till tracing här. Se exempel:  https://github.com/diwise/iot-device-mgmt/blob/main/pkg/client/client.go#L202-L204

2024-01-15 19:26 UTC, istyf commented on pkg/client/client_test.go
> +			response.ContentType("application/json"),
Har responsen den här content typen i vanliga fall?

2024-01-15 19:26 UTC, istyf commented on pkg/client/client.go
> +	CreateUnknownDevice(ctx context.Context, device types.Device) error
Behöver vi olika interface för create known och unknown device?

2024-01-16 07:20 UTC, ermhawi commented on pkg/client/client.go
> +
Fixar det

2024-01-16 07:21 UTC, ermhawi commented on pkg/client/client_test.go
> +			response.ContentType("application/json"),
Slarv av mig, jag tar bort det.

2024-01-16 07:29 UTC, ermhawi commented on pkg/client/client.go
> +	CreateUnknownDevice(ctx context.Context, device types.Device) error
Det är klart att detta är en generell metod som borde kunna användas för att skapa vilken device som helst. Jag döper om den till CreateDevice

2024-01-16 09:06 UTC, istyf approved these changes
/lgtm

2024-01-16 09:07 UTC, merged